---
title: "ITTSA PIZZA"
date: 2019-02-16
---

title: ITTSA PIZZA BLOG!
author: Kseniya Verenich
email: kseniyaverenich@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about what the people really want, PIZZA!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
